language: c
jobs:
  include:
    - os: windows
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os : linux
      dist: xenial
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os : linux
      dist: bionic
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os : linux
      dist: focal
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
    - os : windows
      arch: amd64
      script:
        - clang -coverage -O0 hello_world.c -o hello_world
        - ./hello_world
